dataRoot: ./data
listen: false
port: 8000
whitelistMode: false
enableForwardedWhitelist: true
whitelist:
  - 127.0.0.1
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
enableUserAccounts: false
enableDiscreetLogin: false
cookieSecret: ZvDIBZW3oPYihFzhuWG6mwIijtduxFQSlqvoQ6r/kDVoDYKApfHMmyfYx9ny9oPmk3zSQ/muG6v8+7QyHWxBjw==
disableCsrfProtection: false
securityOverride: true
autorun: true
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: true
skipContentCheck: false
disableChatBackup: false
numberOfBackups: 50
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
enableExtensions: true
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Cohee/jina-embeddings-v2-base-en
  promptExpansionModel: Cohee/fooocus_expansion-onnx
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
mistral:
  enablePrefix: false
enableServerPlugins: false
sessionTimeout: 86400
